# Generated by Django 5.0.2 on 2024-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('building_address', models.CharField(max_length=100)),
                ('landlord_name', models.CharField(max_length=30)),
                ('report', models.TextField(max_length=200)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('verify', models.TextField(choices=[('T', 'True'), ('F', 'False')], default='F')),
                ('feedback', models.TextField(default=' ', max_length=200)),
                ('user', models.CharField(default='ANONYMOUS', max_length=30)),
            ],
        ),
    ]
